### ISSUE TITLE
Error when uploading conductivity project XML

### ISSUE THREAD

**Issue by jesselangdon** [Riverscapes/riverscapestools#1] opened 2017-02-08 04:59 UTC
I tried uploading a conductivity project this evening, and received this error message:

![image](https://cloud.githubusercontent.com/assets/2524993/22724024/3c5e4bc6-ed78-11e6-9448-a5224b8da033.png)

**Comment by MattReimer** [comment] 2017-02-08 17:08
Right. Beleive it or not, this is by design. In order for uploading to work we need to establish where EC goes in the grand scheme:

Take a look at: <https://github.com/Riverscapes/Program/blob/master/Program/Riverscapes.xml>

We're going to need two lines:

A definition line inside the  `<Products>` node: 

```xml
<Product id="EC" name="EC" folder="EC"/>
```
and then a line inside the `<Hierarchy>` telling us where it belongs in the grand scheme of things:

```xml
<Product ref="EC"/>
```

Feel free to make the change yourself or just tell me where in the schema it belongs and I can do it. 

Might as well do solar too while you're at it.

**Comment by MattReimer** [comment] 2017-02-08 17:59
Jesse Closed this:

<https://github.com/Riverscapes/Program/commit/968c52238f52de7928fc008262a6e18507925dfa>

**Closed** 2017-02-08 22:51 UTC
Labels: bug
